"""PreToolUse guard: refuse edits to files that must not be edited in place.

Reads the hook payload on stdin and denies the edit when the target is:

* a migration revision that is already committed (write a new revision instead);
* a generated artifact (``openapi.json``, ``schema.gen.ts``);
* a secrets file (``.env``).

A migration file that is *not* yet tracked by git is a fresh autogenerated
revision, so editing it is allowed - that is the normal way to correct what
Alembic missed.

Deliberately silent (exit 0) on anything it cannot classify: a guard that blocks
on its own bugs is worse than no guard.
"""

from __future__ import annotations

import json
import subprocess
import sys
from pathlib import Path

GENERATED = ("openapi.json", "schema.gen.ts")


def deny(reason: str) -> None:
    json.dump(
        {
            "hookSpecificOutput": {
                "hookEventName": "PreToolUse",
                "permissionDecision": "deny",
                "permissionDecisionReason": reason,
            }
        },
        sys.stdout,
    )
    sys.exit(2)


def is_tracked(path: Path) -> bool:
    try:
        return (
            subprocess.run(
                ["git", "ls-files", "--error-unmatch", str(path)],
                capture_output=True,
                timeout=10,
            ).returncode
            == 0
        )
    except (OSError, subprocess.SubprocessError):
        return False


def main() -> None:
    try:
        payload = json.load(sys.stdin)
    except (json.JSONDecodeError, ValueError):
        return

    raw = (payload.get("tool_input") or {}).get("file_path")
    if not raw:
        return

    path = Path(raw)
    posix = path.as_posix()

    if path.name == ".env":
        deny("Refusing to touch .env - secrets are never edited by an agent.")

    if path.name in GENERATED:
        deny(
            f"{path.name} is generated. Change the source and regenerate it "
            "(`uv run panel openapi` for the API schema)."
        )

    if "core/db/migrations/versions/" in posix and is_tracked(path):
        deny(
            "This migration is already committed and may have been applied. "
            "Create a new revision instead: "
            "`uv run alembic revision --autogenerate -m '...'`."
        )


if __name__ == "__main__":
    main()
