/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Job
         * @description Return one Job's state for frontend polling.
         */
        get: operations["get_job_api_jobs__job_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/{job_id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Cancel Job
         * @description Cancel a queued or running Job, returning its terminal state.
         *
         *     Cancellation is a database-only operation: ``BackgroundTasks`` runs the scan
         *     in a worker thread that cannot be terminated from outside, so a scan already
         *     in flight keeps running to completion. What this guarantees is that the Job
         *     is closed and its result never persisted - the runner re-checks the Job
         *     before ingesting, and ingest refuses a Job that is no longer running.
         *
         *     There is no ``cancelled`` status: a cancelled Job is ``failed`` with the
         *     reason in ``error``, so every consumer that already handles failure handles
         *     this too, and no persisted status is added that nothing would ever produce.
         *     Cancelling a Job that already finished is a ``409`` rather than a silent
         *     no-op - it tells the caller their cancellation changed nothing.
         */
        post: operations["cancel_job_api_jobs__job_id__cancel_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/scan/attention": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Attention
         * @description Reasons the panel wants attention, with the number of services behind each.
         *
         *     The predicates are independent, unlike ``rescan_reason``: a service whose
         *     documents are partial *and* whose scanner is outdated is counted under both
         *     rules, because hiding one behind the other would understate the work.
         */
        get: operations["get_attention_api_scan_attention_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/scan/excluded": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Excluded
         * @description Services deliberately kept out of scanning.
         */
        get: operations["list_excluded_api_scan_excluded_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/scan/ineligible": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Ineligible
         * @description Repositories discovery checked and found to have no API reference.
         *
         *     Kept out of the registry but not out of the database: the result of the
         *     check is what tells an operator the repository was looked at, rather than
         *     missed. ``has_api_ref IS FALSE`` specifically - a NULL is a repository
         *     discovery has not reached yet, which is not the same claim.
         */
        get: operations["list_ineligible_api_scan_ineligible_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/scan/services": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Services
         * @description The registry table: filtered rows plus the count behind every chip.
         *
         *     ``counts`` is computed with the search applied but the status filter
         *     ignored, so the chips keep showing where the rest of the matches went.
         */
        get: operations["list_services_api_scan_services_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/scan/services/{repo}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Service
         * @description Everything the service page shows about one service.
         */
        get: operations["get_service_api_scan_services__repo__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/scan/services/{repo}/documents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Documents
         * @description One page of the active snapshot's API documents.
         *
         *     Pages that carry no scan status are not API documents; they are counted in
         *     the service detail's ``non_endpoint_documents`` instead of being listed here
         *     under a status they never had.
         *
         *     ``section`` and ``section_status`` together answer "which documents have a
         *     failed body": both are required for the filter to apply, because either one
         *     alone would silently mean something else. ``issue`` answers the same
         *     question for a diagnostic code, and ``api_version`` narrows to one version
         *     of the API (``unversioned`` for the documents that name none).
         */
        get: operations["list_documents_api_scan_services__repo__documents_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/scan/services/{repo}/documents/{document_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Document
         * @description One document of the active snapshot, with its sections and parameters.
         */
        get: operations["get_document_api_scan_services__repo__documents__document_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/scan/services/{repo}/exclude": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Exclude Service
         * @description Hide a Service from the registry without deleting anything it owns.
         *
         *     Exclusion is non-destructive: no Job, Snapshot or document row is touched,
         *     so restoring the Service brings back the same history it had. Only the
         *     listing endpoints filter it out - the detail endpoints keep answering, so
         *     the UI can still read an excluded Service in order to restore it.
         *
         *     A Job already queued or running when this lands is deliberately left alone
         *     and will ingest its result normally. Killing it would mean either
         *     discarding a scan that already cost its rate-limit budget, or writing a
         *     half-ingested Snapshot; the exclusion takes effect from the next launch
         *     instead, which ``start_scan`` refuses.
         *
         *     The Service row is locked for the whole check-then-insert, which is what
         *     makes that refusal reliable - see ``start_scan``.
         */
        post: operations["exclude_service_api_scan_services__repo__exclude_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/scan/services/{repo}/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Export Snapshot
         * @description The active snapshot as a ``RepositoryScanResult`` - the scanner's own
         *     contract, not a shape invented for this endpoint.
         *
         *     Rebuilt from the stored payloads and validated on the way out: if anything
         *     in the database no longer satisfies the contract, this fails loudly instead
         *     of handing out a file that only looks right.
         */
        get: operations["export_snapshot_api_scan_services__repo__export_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/scan/services/{repo}/include": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Include Service
         * @description Restore an excluded Service to the registry.
         *
         *     The exclusion row is deleted rather than archived, so no audit trail
         *     survives a restore - the reason text lives only while the exclusion does.
         *     Restoring a Service that is not excluded is a ``409`` rather than a silent
         *     no-op: it tells the caller their request changed nothing.
         */
        post: operations["include_service_api_scan_services__repo__include_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/scan/services/{repo}/rescan": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Start Scan
         * @description Queue a scan Job for an existing Service and schedule it in the background.
         *
         *     The Job is created ``queued`` and committed before scheduling; the Job ID is
         *     returned immediately without waiting for the scan.
         *
         *     An excluded Service is a ``409``. The Service row is locked for the whole
         *     check so this cannot interleave with ``exclude_service``: without the lock
         *     both could read "not excluded yet" and commit, leaving a scan running
         *     against a service the operator had just hidden.
         */
        post: operations["start_scan_api_scan_services__repo__rescan_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/scan/services/{repo}/snapshots": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Snapshots
         * @description A service's scan history, newest first.
         */
        get: operations["list_snapshots_api_scan_services__repo__snapshots_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/scan/services/{repo}/snapshots/{snapshot_id}/activate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Activate Snapshot
         * @description Serve this Service's scan-result views from another of its Snapshots.
         *
         *     Moves ``active_snapshot_id`` only: ``latest_snapshot_id`` and the stored
         *     Snapshots stay as they are, and every view downstream already follows this
         *     pointer. Re-activating the active Snapshot changes nothing and answers 200.
         *     An excluded Service is allowed; ``initiated_by`` is logged, not stored.
         *
         *     Refused with ``409`` while a scan Job is queued or running, whatever the
         *     request would change: ingest moves the same pointer, so one would silently
         *     overwrite the other. Terminal Jobs never block. The Service row is locked
         *     for the check-then-write, as in ``start_scan``.
         */
        post: operations["activate_snapshot_api_scan_services__repo__snapshots__snapshot_id__activate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/scan/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Summary
         * @description Panel-wide counters for the header strip.
         */
        get: operations["get_summary_api_scan_summary_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Report liveness, and any capability the panel knows it is missing.
         */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * ActivateSnapshotRequest
         * @description Body for activating a stored Snapshot: who asked for the switch.
         *
         *     Its own model rather than a reuse of ``ScanRequest``, because the field
         *     means something different here: a scan's initiator is persisted on the Job,
         *     this one is only logged - there is no activation audit table.
         */
        ActivateSnapshotRequest: {
            /** Initiated By */
            initiated_by: string;
        };
        /**
         * AttentionRule
         * @description One reason the panel is asking for attention, with how many services hit it.
         */
        AttentionRule: {
            /** Code */
            code: string;
            /** Count */
            count: number;
            /** Label */
            label: string;
            /** Panel */
            panel: string;
        };
        /**
         * DocumentDetailResponse
         * @description The document drill-down: sections, parameters and diagnostics.
         */
        DocumentDetailResponse: {
            /** Api Version */
            api_version: string | null;
            /** Failure Reason */
            failure_reason: string | null;
            /** Id */
            id: number;
            /** Method */
            method: string | null;
            /** Overall Status */
            overall_status: string | null;
            /** Sections */
            sections: components["schemas"]["SectionDetail"][];
            /** Source Url */
            source_url: string;
            /** Title */
            title: string | null;
            /** Uri */
            uri: string | null;
        };
        /**
         * DocumentListItem
         * @description One row of the documents block.
         */
        DocumentListItem: {
            /** Id */
            id: number;
            /** Issues */
            issues: components["schemas"]["IssueCount"][];
            /** Method */
            method: string | null;
            /** Overall Status */
            overall_status: string;
            /** Path */
            path: string;
            /** Title */
            title: string | null;
            /** Uri */
            uri: string | null;
        };
        /**
         * DocumentsResponse
         * @description One page of a snapshot's documents, with the counts behind the chips.
         */
        DocumentsResponse: {
            /** Doc Counts */
            doc_counts: {
                [key: string]: number;
            };
            /** Items */
            items: components["schemas"]["DocumentListItem"][];
            /** Page */
            page: number;
            /** Page Size */
            page_size: number;
            /** Total */
            total: number;
            /** Version Counts */
            version_counts: {
                [key: string]: number;
            };
        };
        /**
         * ExampleResponse
         * @description One request or response example, as written in the documentation.
         *
         *     ``raw`` is the source text, shown verbatim: the point of an example is to
         *     compare it against what the parser made of it. Whether it was valid JSON is
         *     deliberately absent - not every example is JSON (a request line is a
         *     legitimate example), and the scanner already reports the real defect as an
         *     ``example_invalid_json`` issue on the section.
         */
        ExampleResponse: {
            /** Label */
            label: string | null;
            /** Language */
            language: string | null;
            /** Raw */
            raw: string;
        };
        /**
         * ExcludeRequest
         * @description Body for excluding a service: why, and who decided.
         *
         *     The reason is the entire audit record. Restoring a service deletes its
         *     exclusion row rather than archiving it, so this text is the only thing
         *     that ever explains why the service was hidden - a blank one is refused
         *     rather than stored as whitespace that reads as filled in.
         */
        ExcludeRequest: {
            /** Initiated By */
            initiated_by: string;
            /** Reason */
            reason: string;
        };
        /**
         * ExcludedServiceResponse
         * @description One deliberately excluded service.
         */
        ExcludedServiceResponse: {
            /**
             * Excluded At
             * Format: date-time
             */
            excluded_at: string;
            /** Excluded By */
            excluded_by: string;
            /** Name */
            name: string;
            /** Reason */
            reason: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * HealthResponse
         * @description Whether the panel is fully functional, not merely running.
         *
         *     ``degraded`` still answers ``200``: the panel serves every read endpoint in
         *     that state, and this response is what a container healthcheck polls. Failing
         *     the check would stop the frontend from starting over a janitorial problem,
         *     which is a worse outcome than the problem.
         */
        HealthResponse: {
            /** Detail */
            detail?: string | null;
            /**
             * Status
             * @enum {string}
             */
            status: "ok" | "degraded";
        };
        /**
         * IneligibleRepositoryResponse
         * @description One repository discovery checked and found to have no API reference.
         *
         *     Distinct from an excluded service: nobody decided this, a lookup did, and
         *     it reverses itself the moment the repository gains the path. ``checked_at``
         *     is what makes the row readable - without the date, "ineligible" carries no
         *     hint of how stale the finding is.
         */
        IneligibleRepositoryResponse: {
            /** Branch */
            branch: string;
            /** Checked At */
            checked_at: string | null;
            /** Name */
            name: string;
            /** Repo */
            repo: string;
        };
        /**
         * IssueCount
         * @description One issue code and how often it occurred.
         */
        IssueCount: {
            /** Code */
            code: string;
            /** Count */
            count: number;
        };
        /**
         * JobKind
         * @enum {string}
         */
        JobKind: "scan" | "generate" | "maintain";
        /**
         * JobResponse
         * @description Job view for frontend polling (GET /api/jobs/{id}).
         */
        JobResponse: {
            /** Commit Hash */
            commit_hash: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Error */
            error: string | null;
            /** Finished At */
            finished_at: string | null;
            /** Id */
            id: number;
            kind: components["schemas"]["JobKind"];
            /** Repository */
            repository: string;
            /** Scanner Version */
            scanner_version: string | null;
            /** Service Id */
            service_id: number;
            /** Started At */
            started_at: string | null;
            status: components["schemas"]["JobStatus"];
        };
        /**
         * JobStatus
         * @enum {string}
         */
        JobStatus: "queued" | "running" | "done" | "failed";
        /**
         * ParameterResponse
         * @description One parameter row, nested exactly as the scan recorded it.
         */
        ParameterResponse: {
            /** Children */
            children?: components["schemas"]["ParameterResponse"][] | null;
            /** Description */
            description: string;
            /** Mandatory */
            mandatory: boolean;
            /** Name */
            name: string;
            /** Param Type */
            param_type: string;
        };
        /**
         * RescanReason
         * @description Why the panel suggests rescanning, in priority order.
         *
         *     Documents that came out partial are deliberately not a reason: the same
         *     commit scanned by the same scanner produces the same result, so offering a
         *     rescan would promise a change that cannot happen. Partial documents are a
         *     documentation problem, and the panel reports them as one.
         * @enum {string}
         */
        RescanReason: "retry" | "version" | "drift";
        /**
         * ScanRequest
         * @description Body for launching a scan: who initiated it.
         */
        ScanRequest: {
            /** Initiated By */
            initiated_by: string;
        };
        /**
         * ScanStatus
         * @description How completely the panel managed to read a service.
         *
         *     This is a statement about the scan, not about the documentation. A document
         *     full of malformed tables that we nevertheless read end to end leaves the
         *     service ``scanned``; its quality is reported separately as the clean-document
         *     share. ``partial`` means something stayed unread: a document we could not
         *     interpret at all, or parameter rows we could not recognize.
         * @enum {string}
         */
        ScanStatus: "scanned" | "partial" | "failed" | "not_scanned" | "scanning";
        /**
         * SectionDetail
         * @description One endpoint section as the drill-down renders it.
         */
        SectionDetail: {
            /** Examples */
            examples: components["schemas"]["ExampleResponse"][];
            /** Fields Recognized */
            fields_recognized: number;
            /** Fields Total */
            fields_total: number;
            /** Fields Unknown Type */
            fields_unknown_type: number;
            /** Issues */
            issues: {
                [key: string]: string | null;
            }[];
            /** Name */
            name: string;
            /** Parameters */
            parameters: components["schemas"]["ParameterResponse"][] | null;
            /** Status */
            status: string;
        };
        /**
         * ServiceDetailResponse
         * @description The service page: the registry row plus what only the detail view shows.
         */
        ServiceDetailResponse: {
            active_snapshot: components["schemas"]["SnapshotResponse"] | null;
            /** Docs Changed */
            docs_changed: boolean;
            /** Docs Ok */
            docs_ok: number | null;
            /** Documents */
            documents: number | null;
            /** Error */
            error: string | null;
            /** Error At */
            error_at: string | null;
            /** Head Commit */
            head_commit: string | null;
            /** Initiated By */
            initiated_by?: string | null;
            /** Interruption */
            interruption: {
                [key: string]: unknown;
            } | null;
            /** Job Id */
            job_id?: number | null;
            /** Label */
            label: string;
            latest_snapshot: components["schemas"]["SnapshotResponse"] | null;
            /** Name */
            name: string;
            /** Non Endpoint Documents */
            non_endpoint_documents: number;
            /** Overall Breakdown */
            overall_breakdown: {
                [key: string]: number;
            };
            /** Read In Full */
            read_in_full: number | null;
            rescan_reason: components["schemas"]["RescanReason"] | null;
            /** Rows Unrecognized */
            rows_unrecognized: number;
            scan_status: components["schemas"]["ScanStatus"];
            /** Scanned At */
            scanned_at: string | null;
            /** Scanner Version */
            scanner_version: string | null;
            /** Section Rollup */
            section_rollup: {
                [key: string]: {
                    [key: string]: number;
                };
            };
            /** Started At */
            started_at?: string | null;
            /** Top Issues */
            top_issues: components["schemas"]["IssueCount"][];
            /** Unread Breakdown */
            unread_breakdown: {
                [key: string]: number;
            };
            /** Unread Documents */
            unread_documents: number;
        };
        /**
         * ServiceListItem
         * @description One row of the registry, served from the service's active Snapshot.
         *
         *     ``documents`` counts the documents that have a scan status, so it always
         *     equals the sum of ``overall_breakdown``. Pages that are not API documents
         *     are counted separately (see ``ServiceDetailResponse.non_endpoint_documents``)
         *     rather than folded into a status they do not have.
         */
        ServiceListItem: {
            /** Docs Changed */
            docs_changed: boolean;
            /** Docs Ok */
            docs_ok: number | null;
            /** Documents */
            documents: number | null;
            /** Error */
            error: string | null;
            /** Error At */
            error_at: string | null;
            /** Initiated By */
            initiated_by?: string | null;
            /** Job Id */
            job_id?: number | null;
            /** Label */
            label: string;
            /** Name */
            name: string;
            /** Overall Breakdown */
            overall_breakdown: {
                [key: string]: number;
            };
            /** Read In Full */
            read_in_full: number | null;
            rescan_reason: components["schemas"]["RescanReason"] | null;
            /** Rows Unrecognized */
            rows_unrecognized: number;
            scan_status: components["schemas"]["ScanStatus"];
            /** Scanned At */
            scanned_at: string | null;
            /** Scanner Version */
            scanner_version: string | null;
            /** Section Rollup */
            section_rollup: {
                [key: string]: {
                    [key: string]: number;
                };
            };
            /** Started At */
            started_at?: string | null;
            /** Unread Breakdown */
            unread_breakdown: {
                [key: string]: number;
            };
            /** Unread Documents */
            unread_documents: number;
        };
        /**
         * ServicesResponse
         * @description The registry: matching rows plus the count behind every filter chip.
         */
        ServicesResponse: {
            /** Counts */
            counts: {
                [key: string]: number;
            };
            /** Items */
            items: components["schemas"]["ServiceListItem"][];
        };
        /**
         * SnapshotResponse
         * @description One persisted scan snapshot (the `snapshot` row).
         */
        SnapshotResponse: {
            /** Branch */
            branch: string;
            /** Commit Hash */
            commit_hash: string;
            /** Completeness */
            completeness: number | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Docs Ok */
            docs_ok: number | null;
            /** Document Schema Version */
            document_schema_version: string;
            /** Documents Total */
            documents_total: number;
            /** Endpoints Total */
            endpoints_total: number;
            /** Failed Count */
            failed_count: number;
            /** Id */
            id: number;
            /** Issues Total */
            issues_total: number;
            /**
             * Last Scanned At
             * Format: date-time
             */
            last_scanned_at: string;
            /** Non Endpoint Documents */
            non_endpoint_documents: number;
            /** Ok Count */
            ok_count: number;
            /** Parser Ok */
            parser_ok: number | null;
            /** Partial Count */
            partial_count: number;
            /** Scanner Version */
            scanner_version: string;
            /** Source Job Id */
            source_job_id: number;
            /** Unsupported Count */
            unsupported_count: number;
        };
        /**
         * SnapshotsResponse
         * @description A service's snapshot history, newest first.
         */
        SnapshotsResponse: {
            /** Active Id */
            active_id: number | null;
            /** Items */
            items: components["schemas"]["SnapshotResponse"][];
            /** Latest Id */
            latest_id: number | null;
        };
        /**
         * StartScanResponse
         * @description Returned immediately when a scan Job is queued.
         */
        StartScanResponse: {
            /** Job Id */
            job_id: number;
        };
        /**
         * SummaryResponse
         * @description The header strip: one number per thing the panel is currently doing.
         */
        SummaryResponse: {
            /** Documents Total */
            documents_total: number;
            /** Failed Services */
            failed_services: number;
            /** Scanner Version */
            scanner_version: string;
            /** Scans Running */
            scans_running: number;
            /** Services Total */
            services_total: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_job_api_jobs__job_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancel_job_api_jobs__job_id__cancel_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_attention_api_scan_attention_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AttentionRule"][];
                };
            };
        };
    };
    list_excluded_api_scan_excluded_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExcludedServiceResponse"][];
                };
            };
        };
    };
    list_ineligible_api_scan_ineligible_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IneligibleRepositoryResponse"][];
                };
            };
        };
    };
    list_services_api_scan_services_get: {
        parameters: {
            query?: {
                status?: string;
                q?: string;
                sort?: string;
                rule?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ServicesResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_service_api_scan_services__repo__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                repo: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ServiceDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_documents_api_scan_services__repo__documents_get: {
        parameters: {
            query?: {
                status?: string | null;
                q?: string;
                page?: number;
                section?: string | null;
                section_status?: string | null;
                issue?: string | null;
                api_version?: string | null;
            };
            header?: never;
            path: {
                repo: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_document_api_scan_services__repo__documents__document_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                repo: string;
                document_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    exclude_service_api_scan_services__repo__exclude_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                repo: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExcludeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    export_snapshot_api_scan_services__repo__export_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                repo: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    include_service_api_scan_services__repo__include_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                repo: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    start_scan_api_scan_services__repo__rescan_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                repo: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ScanRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StartScanResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_snapshots_api_scan_services__repo__snapshots_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                repo: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SnapshotsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    activate_snapshot_api_scan_services__repo__snapshots__snapshot_id__activate_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                repo: string;
                snapshot_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ActivateSnapshotRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SnapshotsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_summary_api_scan_summary_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SummaryResponse"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
}
