"""initial schema: job, service, document, issue

Revision ID: 565450797c8c
Revises: 
Create Date: 2026-07-02 12:25:08.242632

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '565450797c8c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.Enum('scan', 'generate', 'maintain', name='jobkind', native_enum=False), nullable=False),
    sa.Column('target', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('queued', 'running', 'done', 'failed', name='jobstatus', native_enum=False), nullable=False),
    sa.Column('scanner_version', sa.String(), nullable=True),
    sa.Column('commit_hash', sa.String(), nullable=True),
    sa.Column('docs_total', sa.Integer(), nullable=True),
    sa.Column('ok_count', sa.Integer(), nullable=True),
    sa.Column('partial_count', sa.Integer(), nullable=True),
    sa.Column('failed_count', sa.Integer(), nullable=True),
    sa.Column('unsupported_count', sa.Integer(), nullable=True),
    sa.Column('issues_count', sa.Integer(), nullable=True),
    sa.Column('error', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_job'))
    )
    op.create_table('service',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('repo', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('branch', sa.String(), nullable=False),
    sa.Column('has_api_ref', sa.Boolean(), nullable=False),
    sa.Column('error', sa.String(), nullable=True),
    sa.Column('scanned_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('scanner_version', sa.String(), nullable=True),
    sa.Column('commit_hash', sa.String(), nullable=True),
    sa.Column('head_commit', sa.String(), nullable=True),
    sa.Column('non_endpoint_documents', sa.Integer(), nullable=True),
    sa.Column('current_job_id', sa.Integer(), nullable=True),
    sa.Column('previous_job_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['current_job_id'], ['job.id'], name=op.f('fk_service_current_job_id_job')),
    sa.ForeignKeyConstraint(['previous_job_id'], ['job.id'], name=op.f('fk_service_previous_job_id_job')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_service')),
    sa.UniqueConstraint('repo', name=op.f('uq_service_repo'))
    )
    op.create_table('document',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('service_id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('document', sa.String(), nullable=False),
    sa.Column('method', sa.String(), nullable=True),
    sa.Column('uri', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('api_version', sa.String(), nullable=True),
    sa.Column('failure_reason', sa.String(), nullable=True),
    sa.Column('overall_status', sa.Enum('ok', 'partial', 'unsupported', 'failed', name='docstatus', native_enum=False), nullable=False),
    sa.Column('completeness', sa.Float(), nullable=False),
    sa.Column('sections', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['job.id'], name=op.f('fk_document_job_id_job')),
    sa.ForeignKeyConstraint(['service_id'], ['service.id'], name=op.f('fk_document_service_id_service')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_document')),
    sa.UniqueConstraint('job_id', 'document', name=op.f('uq_document_job_id'))
    )
    with op.batch_alter_table('document', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_document_job_id'), ['job_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_document_service_id'), ['service_id'], unique=False)

    op.create_table('issue',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('service_id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('details', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['document.id'], name=op.f('fk_issue_document_id_document'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['job_id'], ['job.id'], name=op.f('fk_issue_job_id_job')),
    sa.ForeignKeyConstraint(['service_id'], ['service.id'], name=op.f('fk_issue_service_id_service')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_issue'))
    )
    with op.batch_alter_table('issue', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_issue_code'), ['code'], unique=False)
        batch_op.create_index(batch_op.f('ix_issue_job_id'), ['job_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('issue', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_issue_job_id'))
        batch_op.drop_index(batch_op.f('ix_issue_code'))

    op.drop_table('issue')
    with op.batch_alter_table('document', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_document_service_id'))
        batch_op.drop_index(batch_op.f('ix_document_job_id'))

    op.drop_table('document')
    op.drop_table('service')
    op.drop_table('job')
    # ### end Alembic commands ###
