"""postgresql initial schema: service, job, generation, document

Revision ID: c75cdb74675c
Revises: 
Create Date: 2026-07-23 15:36:21.976987

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c75cdb74675c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('service',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('repo', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('branch', sa.String(length=255), nullable=False),
    sa.Column('has_api_ref', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('is_excluded', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('first_seen', sa.DateTime(timezone=True), nullable=True),
    sa.Column('eligibility_checked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('discovery_error', sa.Text(), nullable=True),
    sa.Column('head_commit', sa.String(length=64), nullable=True),
    sa.Column('active_generation_id', sa.Integer(), nullable=True),
    sa.Column('latest_generation_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_service')),
    sa.UniqueConstraint('repo', name=op.f('uq_service_repo'))
    )
    op.create_index(op.f('ix_service_active_generation_id'), 'service', ['active_generation_id'], unique=False)
    op.create_index('ix_service_eligibility', 'service', ['has_api_ref', 'is_excluded'], unique=False)
    op.create_index(op.f('ix_service_latest_generation_id'), 'service', ['latest_generation_id'], unique=False)
    op.create_table('job',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('service_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.Enum('scan', 'generate', 'maintain', name='job_kind', native_enum=False), server_default='scan', nullable=False),
    sa.Column('status', sa.Enum('queued', 'running', 'done', 'failed', name='job_status', native_enum=False), server_default='queued', nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('interruption', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("\n            (\n                status = 'queued'\n                AND started_at IS NULL\n                AND finished_at IS NULL\n            )\n            OR\n            (\n                status = 'running'\n                AND started_at IS NOT NULL\n                AND finished_at IS NULL\n            )\n            OR\n            (\n                status = 'done'\n                AND started_at IS NOT NULL\n                AND finished_at IS NOT NULL\n            )\n            OR\n            (\n                status = 'failed'\n                AND finished_at IS NOT NULL\n            )\n            ", name=op.f('ck_job_status_timestamps')),
    sa.CheckConstraint("status != 'failed' OR error IS NOT NULL", name=op.f('ck_job_failed_job_has_error')),
    sa.ForeignKeyConstraint(['service_id'], ['service.id'], name=op.f('fk_job_service_id_service'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_job'))
    )
    op.create_index('ix_job_service_created_at', 'job', ['service_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_job_service_id'), 'job', ['service_id'], unique=False)
    op.create_index('ix_job_service_status', 'job', ['service_id', 'status'], unique=False)
    op.create_index(op.f('ix_job_status'), 'job', ['status'], unique=False)
    op.create_index('uq_active_scan_job_per_service', 'job', ['service_id'], unique=True, postgresql_where=sa.text("kind = 'scan' AND status IN ('queued', 'running')"))
    op.create_table('generation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('service_id', sa.Integer(), nullable=False),
    sa.Column('source_job_id', sa.Integer(), nullable=False),
    sa.Column('branch', sa.String(length=255), nullable=False),
    sa.Column('commit_hash', sa.String(length=64), nullable=False),
    sa.Column('scanner_version', sa.String(length=255), nullable=False),
    sa.Column('document_schema_version', sa.String(length=100), nullable=False),
    sa.Column('incomplete_reason', sa.Text(), nullable=True),
    sa.Column('excluded_documents', postgresql.ARRAY(sa.Text()), server_default=sa.text("'{}'::text[]"), nullable=False),
    sa.Column('documents_total', sa.Integer(), server_default='0', nullable=False),
    sa.Column('endpoints_total', sa.Integer(), server_default='0', nullable=False),
    sa.Column('non_endpoint_documents', sa.Integer(), server_default='0', nullable=False),
    sa.Column('issues_total', sa.Integer(), server_default='0', nullable=False),
    sa.Column('ok_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('partial_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('failed_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('unsupported_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('completeness', sa.Float(), nullable=True),
    sa.Column('analytics', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('\n            endpoints_total + non_endpoint_documents = documents_total\n            ', name=op.f('ck_generation_document_counts_match')),
    sa.CheckConstraint('\n            ok_count >= 0\n            AND partial_count >= 0\n            AND failed_count >= 0\n            AND unsupported_count >= 0\n            ', name=op.f('ck_generation_status_counts_non_negative')),
    sa.CheckConstraint('documents_total >= 0', name=op.f('ck_generation_documents_total_non_negative')),
    sa.CheckConstraint('endpoints_total >= 0', name=op.f('ck_generation_endpoints_total_non_negative')),
    sa.CheckConstraint('issues_total >= 0', name=op.f('ck_generation_issues_total_non_negative')),
    sa.CheckConstraint('non_endpoint_documents >= 0', name=op.f('ck_generation_non_endpoint_documents_non_negative')),
    sa.ForeignKeyConstraint(['service_id'], ['service.id'], name=op.f('fk_generation_service_id_service'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_job_id'], ['job.id'], name=op.f('fk_generation_source_job_id_job'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_generation')),
    sa.UniqueConstraint('source_job_id', name=op.f('uq_generation_source_job_id'))
    )
    op.create_index(op.f('ix_generation_commit_hash'), 'generation', ['commit_hash'], unique=False)
    op.create_index(op.f('ix_generation_created_at'), 'generation', ['created_at'], unique=False)
    op.create_index('ix_generation_service_created_at', 'generation', ['service_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_generation_service_id'), 'generation', ['service_id'], unique=False)
    # Deferred (use_alter) foreign keys from service to generation; created
    # here because generation does not exist yet when service is created.
    op.create_foreign_key('fk_service_active_generation', 'service', 'generation', ['active_generation_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('fk_service_latest_generation', 'service', 'generation', ['latest_generation_id'], ['id'], ondelete='SET NULL')
    op.create_table('document',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('generation_id', sa.Integer(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('kind', sa.Text(), sa.Computed("payload ->> 'kind'", persisted=True), nullable=False),
    sa.Column('path', sa.Text(), sa.Computed("payload ->> 'path'", persisted=True), nullable=False),
    sa.Column('title', sa.Text(), sa.Computed("payload ->> 'title'", persisted=True), nullable=True),
    sa.Column('method', sa.Text(), sa.Computed("payload ->> 'method'", persisted=True), nullable=True),
    sa.Column('uri', sa.Text(), sa.Computed("payload ->> 'uri'", persisted=True), nullable=True),
    sa.Column('api_version', sa.Text(), sa.Computed("payload ->> 'api_version'", persisted=True), nullable=True),
    sa.Column('overall_status', sa.String(length=32), nullable=True),
    sa.Column('completeness', sa.Float(), nullable=True),
    sa.Column('issues_count', sa.Integer(), server_default='0', nullable=False),
    sa.CheckConstraint("jsonb_typeof(payload) = 'object'", name=op.f('ck_document_payload_is_object')),
    sa.CheckConstraint("kind = 'endpoint' OR (method IS NULL AND uri IS NULL)", name=op.f('ck_document_non_endpoint_has_no_method_uri')),
    sa.CheckConstraint("kind IN ('document', 'endpoint')", name=op.f('ck_document_kind_valid')),
    sa.CheckConstraint('issues_count >= 0', name=op.f('ck_document_issues_count_non_negative')),
    sa.ForeignKeyConstraint(['generation_id'], ['generation.id'], name=op.f('fk_document_generation_id_generation'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_document')),
    sa.UniqueConstraint('generation_id', 'path', name='uq_document_generation_path')
    )
    op.create_index('ix_document_generation_api_version', 'document', ['generation_id', 'api_version'], unique=False)
    op.create_index(op.f('ix_document_generation_id'), 'document', ['generation_id'], unique=False)
    op.create_index('ix_document_generation_kind', 'document', ['generation_id', 'kind'], unique=False)
    op.create_index('ix_document_generation_method', 'document', ['generation_id', 'method'], unique=False)
    op.create_index('ix_document_generation_status', 'document', ['generation_id', 'overall_status'], unique=False)
    op.create_index(op.f('ix_document_overall_status'), 'document', ['overall_status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_service_active_generation', 'service', type_='foreignkey')
    op.drop_constraint('fk_service_latest_generation', 'service', type_='foreignkey')
    op.drop_index(op.f('ix_document_overall_status'), table_name='document')
    op.drop_index('ix_document_generation_status', table_name='document')
    op.drop_index('ix_document_generation_method', table_name='document')
    op.drop_index('ix_document_generation_kind', table_name='document')
    op.drop_index(op.f('ix_document_generation_id'), table_name='document')
    op.drop_index('ix_document_generation_api_version', table_name='document')
    op.drop_table('document')
    op.drop_index(op.f('ix_generation_service_id'), table_name='generation')
    op.drop_index('ix_generation_service_created_at', table_name='generation')
    op.drop_index(op.f('ix_generation_created_at'), table_name='generation')
    op.drop_index(op.f('ix_generation_commit_hash'), table_name='generation')
    op.drop_table('generation')
    op.drop_index('uq_active_scan_job_per_service', table_name='job', postgresql_where=sa.text("kind = 'scan' AND status IN ('queued', 'running')"))
    op.drop_index(op.f('ix_job_status'), table_name='job')
    op.drop_index('ix_job_service_status', table_name='job')
    op.drop_index(op.f('ix_job_service_id'), table_name='job')
    op.drop_index('ix_job_service_created_at', table_name='job')
    op.drop_table('job')
    op.drop_index(op.f('ix_service_latest_generation_id'), table_name='service')
    op.drop_index('ix_service_eligibility', table_name='service')
    op.drop_index(op.f('ix_service_active_generation_id'), table_name='service')
    op.drop_table('service')
    # ### end Alembic commands ###
