import { beforeEach, describe, expect, it, vi } from "vitest";
import { fireEvent, screen, waitFor, within } from "@testing-library/react";
import { Route, Routes, useLocation } from "react-router";
import { renderPage } from "../../../test/render";
import { tokenWithRoles } from "../../../test/token";
import { keys } from "../../scan/api/queries";
import {
  confirmResource,
  generationAttention,
  generationResources,
  generationSpec,
  liveCall,
  refreshPullRequest,
  resetGenerationMock,
  startGeneration,
} from "../data/mock";
import { GenerationResultPage } from "./GenerationResultPage";
import { GenerationServicePage } from "./GenerationServicePage";
import { GenerationSpecPage } from "./GenerationSpecPage";

/** The session the mocked provider hands back; each test sets the roles. */
const session = vi.hoisted(() => ({ token: "" }));

vi.mock("react-oidc-context", () => ({
  useAuth: () => ({
    user: { access_token: session.token, profile: { preferred_username: "ada@otc.test" } },
    isAuthenticated: true,
    isLoading: false,
    signinRedirect: vi.fn(),
    signoutRedirect: vi.fn(),
  }),
}));

/* The mock lives in module memory, and the refreshes and generations below change it. */
beforeEach(() => {
  resetGenerationMock();
  session.token = tokenWithRoles("worker");
});

/** Where the page navigated to. */
function Location() {
  const { pathname, search } = useLocation();
  return <output data-testid="location">{pathname + search}</output>;
}

function resultPage(path = "/generation/billing-api/result/v1/v1_invoices", seed: [readonly unknown[], unknown][] = []) {
  return renderPage(
    <>
      <GenerationResultPage />
      <Location />
    </>,
    { path, route: "/generation/:name/result/:version/:resource", seed },
  );
}

/** The card, the spec and the result under their own routes, so each can be left for the next. */
function panel(path: string, seed: [readonly unknown[], unknown][] = []) {
  return renderPage(
    <>
      <Routes>
        <Route path="generation/:name" element={<GenerationServicePage />} />
        <Route path="generation/:name/spec/:version/:resource" element={<GenerationSpecPage />} />
        <Route path="generation/:name/result/:version/:resource" element={<GenerationResultPage />} />
      </Routes>
      <Location />
    </>,
    { path, route: "*", seed },
  );
}

const location = () => screen.getByTestId("location").textContent;
/** An operation of the live check, by the SDK method it calls. */
const operation = (sdk: string) => screen.getByRole("group", { name: sdk });
/** Open or close an operation of the live check by its row, the first of its buttons. */
const toggle = (sdk: string) => fireEvent.click(within(operation(sdk)).getAllByRole("button")[0]);
/** The folding group of an operation's path or query parameters. */
const params = (sdk: string, label: "Path" | "Query") =>
  within(operation(sdk)).getByRole("button", { name: new RegExp(`^${label}`) });
const send = (sdk: string) => fireEvent.click(within(operation(sdk)).getByRole("button", { name: /^(Send request|Call again)$/ }));
const DATE = /\d\d\/\d\d\/2026, \d\d:\d\d/.source;

describe("the result of invoices v1: its pull request in review", () => {
  it("shows the generation, the pull request open on GitHub, and a live check of the GET operations only", async () => {
    resultPage();

    expect(screen.getByText("Loading service…")).toBeInTheDocument();
    expect(await screen.findByRole("heading", { name: "billing_api.invoices" })).toBeInTheDocument();
    expect(screen.getByText("Waiting for review")).toBeInTheDocument();
    expect(screen.getByText("Python SDK")).toBeInTheDocument();
    expect(
      screen.getByText(new RegExp(`^4 methods · 2 classes · generated by valeriia · ${DATE}$`)),
    ).toBeInTheDocument();
    expect(screen.getByRole("link", { name: "billing-api layout" })).toHaveAttribute("href", "/generation/billing-api");

    const pr = screen.getByRole("link", { name: "PR #131" });
    expect(pr).toHaveAttribute("href", "https://github.com/opentelekomcloud/python-t-cloud/pull/131");
    expect(pr).toHaveAttribute(
      "title",
      "feat(invoices): generate billing_api.invoices from v1 docs · branch gen/billing_api-invoices",
    );
    expect(screen.getByText("open")).toBeInTheDocument();
    expect(screen.getByRole("button", { name: "Refresh PR state" })).toHaveAttribute(
      "title",
      "Pick up the pull request state from GitHub",
    );
    expect(screen.queryByText(/^Merged —/)).toBeNull();

    expect(screen.getByText("Live check")).toBeInTheDocument();
    expect(screen.getByText("real OTC calls — nothing here is mocked")).toBeInTheDocument();
    expect(screen.getByRole("button", { name: "Run all" })).toBeInTheDocument();
    // the create and the delete are not called live (owner decision)
    expect(screen.getAllByRole("group")).toHaveLength(2);
    expect(within(operation("invoices.list()")).getByText("/v1/billing/invoices")).toBeInTheDocument();
    expect(within(operation("invoices.list()")).getByText("not run")).toBeInTheDocument();
    expect(within(operation("invoices.get()")).getByText("/v1/billing/invoices/{invoice_id}")).toBeInTheDocument();
    expect(within(operation("invoices.get()")).getByText("not run")).toBeInTheDocument();
    expect(screen.queryByText(/invoices\.(create|delete)\(\)/)).toBeNull();
    // no body, no cleanup, no objects left behind (owner decision)
    expect(screen.queryByText(/Body|cleanup|Clean up|left behind/i)).toBeNull();
    // nothing is open until an operation is clicked
    expect(screen.queryByRole("button", { name: "Send request" })).toBeNull();
  });

  it("calls a list with its query, prefilled with a page of 20, and shows what OTC answered", async () => {
    resultPage();

    await screen.findByRole("heading", { name: "billing_api.invoices" });
    toggle("invoices.list()");

    const list = operation("invoices.list()");
    // no path parameter to fill in; the query stays folded, and says what goes out
    expect(within(list).queryByRole("button", { name: /^Path/ })).toBeNull();
    const query = params("invoices.list()", "Query");
    expect(query).toHaveTextContent(/^Query\?limit=20$/);
    expect(query).toHaveAttribute("aria-expanded", "false");
    expect(
      within(list).getByText("No call yet — check the request on the left and press Send request."),
    ).toBeInTheDocument();
    expect(
      within(list).getByText("against billing_api · region eu-de · project from panel credentials"),
    ).toBeInTheDocument();

    fireEvent.click(query);
    expect(within(list).getByRole("textbox", { name: "limit" })).toHaveValue("20");
    expect(within(list).getByText("limit")).toHaveAttribute("title", "optional · Number of records returned");
    expect(within(list).getByText("Integer")).toBeInTheDocument();
    for (const param of ["marker", "sort_key", "status"]) {
      expect(within(list).getByRole("textbox", { name: param })).toHaveValue("");
    }
    expect(within(list).getByText("status")).toHaveAttribute("title", "optional · Filter by invoice status");

    fireEvent.change(within(list).getByRole("textbox", { name: "status" }), { target: { value: "paid out" } });
    expect(params("invoices.list()", "Query")).toHaveTextContent(/^Query\?limit=20&status=paid%20out$/);
    fireEvent.change(within(list).getByRole("textbox", { name: "limit" }), { target: { value: "" } });
    expect(params("invoices.list()", "Query")).toHaveTextContent(/^Query\?status=paid%20out$/);

    send("invoices.list()");

    expect(await within(list).findByText("live ok")).toBeInTheDocument();
    expect(within(list).getByText("200")).toBeInTheDocument();
    expect(within(list).getByText("OK")).toBeInTheDocument();
    expect(within(list).getAllByText("480 ms")).toHaveLength(2);
    const body = JSON.parse(within(list).getByText(/"count": 1/).textContent ?? "");
    expect(body).toEqual({
      invoices: [
        {
          id: "invoice-3f9c",
          project_id: "project_id-value",
          amount: 1200,
          items: "items-value",
          created_at: "2026-08-12T08:41:07Z",
        },
      ],
      count: 1,
    });
    expect(within(list).getByRole("button", { name: "Call again" })).toBeInTheDocument();
    expect(within(list).queryByText(/^No call yet/)).toBeNull();
  });

  it("calls a get: an empty path parameter is not found, a filled one is", async () => {
    resultPage();

    await screen.findByRole("heading", { name: "billing_api.invoices" });
    toggle("invoices.get()");

    const get = operation("invoices.get()");
    // the path is there to fill in, and open
    expect(params("invoices.get()", "Path")).toHaveTextContent(/^Path1 param$/);
    expect(params("invoices.get()", "Path")).toHaveAttribute("aria-expanded", "true");
    const id = within(get).getByRole("textbox", { name: "invoice_id" });
    expect(id).toHaveAttribute("placeholder", "id of invoice");
    expect(params("invoices.get()", "Query")).toHaveTextContent(/^Query1 param · none set$/);

    send("invoices.get()");

    expect(await within(get).findByText("failed")).toBeInTheDocument();
    expect(within(get).getByText("404")).toBeInTheDocument();
    expect(within(get).getByText("Not Found")).toBeInTheDocument();
    expect(within(get).getByText("240 ms · request id req-1f3a91")).toBeInTheDocument();
    expect(within(get).getByText("Resource not found")).toBeInTheDocument();
    expect(
      within(get).getByText(
        "The path parameter invoice_id is empty, so the SDK called the collection URL with a trailing slash. Fill it in with a real id.",
      ),
    ).toBeInTheDocument();
    expect(JSON.parse(within(get).getByText(/APIGW\.0301/).textContent ?? "")).toEqual({
      error_code: "APIGW.0301",
      error_msg: "resource not found",
      request_id: "req-1f3a91",
    });

    fireEvent.change(id, { target: { value: "invoice-3f9c" } });
    send("invoices.get()");

    expect(await within(get).findByText("live ok")).toBeInTheDocument();
    expect(JSON.parse(within(get).getByText(/"invoice":/).textContent ?? "")).toMatchObject({
      invoice: { id: "invoice-3f9c", amount: 1200 },
    });
    expect(within(get).queryByText("Resource not found")).toBeNull();
    // the path group folds, and keeps what was typed
    fireEvent.click(params("invoices.get()", "Path"));
    expect(within(get).queryByRole("textbox", { name: "invoice_id" })).toBeNull();
    fireEvent.click(params("invoices.get()", "Path"));
    expect(within(get).getByRole("textbox", { name: "invoice_id" })).toHaveValue("invoice-3f9c");
  });

  it("keeps one operation open at a time, and runs all of them at once", async () => {
    resultPage();

    await screen.findByRole("heading", { name: "billing_api.invoices" });
    toggle("invoices.list()");
    expect(within(operation("invoices.list()")).getByRole("button", { name: "Send request" })).toBeInTheDocument();
    toggle("invoices.get()");
    expect(within(operation("invoices.list()")).queryByRole("button", { name: "Send request" })).toBeNull();
    expect(within(operation("invoices.get()")).getByRole("button", { name: "Send request" })).toBeInTheDocument();
    toggle("invoices.get()");
    expect(screen.queryByRole("button", { name: "Send request" })).toBeNull();

    fireEvent.click(screen.getByRole("button", { name: "Run all" }));

    expect(await within(operation("invoices.list()")).findByText("live ok")).toBeInTheDocument();
    expect(await within(operation("invoices.get()")).findByText("failed")).toBeInTheDocument();
    expect(within(operation("invoices.get()")).getByText("240 ms")).toBeInTheDocument();
  });

  it("picks the merge up from GitHub: merged, by whom and when, and the live check stays", async () => {
    resultPage();

    fireEvent.click(await screen.findByRole("button", { name: "Refresh PR state" }));

    expect(await screen.findByText("Merged")).toBeInTheDocument();
    expect(screen.getByText("merged")).toBeInTheDocument();
    expect(screen.queryByText("open")).toBeNull();
    expect(screen.queryByRole("button", { name: "Refresh PR state" })).toBeNull();
    expect(
      screen.getByText(
        new RegExp(`^4 methods · 2 classes · generated by valeriia · ${DATE} · merged by valeriia · ${DATE}$`),
      ),
    ).toBeInTheDocument();
    expect(
      screen.getByText("Merged — this resource left Generation and is maintained from the Maintenance panel now."),
    ).toBeInTheDocument();
    // there is no way into Maintenance (owner decision)
    expect(screen.queryByRole("button", { name: /Maintenance/ })).toBeNull();
    expect(screen.getByRole("link", { name: "PR #131" })).toBeInTheDocument();
    expect(screen.getByText("Live check")).toBeInTheDocument();

    // who merged it and when is GitHub's, not who asked
    expect(generationResources("billing-api").find((r) => r.id === "v1_invoices")?.jobs.python).toEqual({
      id: 2088,
      status: "merged",
      pr: 131,
      startedBy: "valeriia",
      startedAt: "2026-08-11T14:20:00Z",
      mergedBy: "valeriia",
      mergedAt: "2026-08-12T09:24:00Z",
      error: null,
    });
    expect(generationAttention().find((r) => r.code === "gen_review")).toBeUndefined();
  });

  it("says why a live call was refused and keeps the page; a refused refresh brings the jobs as they are", async () => {
    // the page believes payments is in review with a pull request; the mock never generated it
    const stale = generationResources("billing-api").map((r) =>
      r.id === "v1_payments"
        ? {
            ...r,
            jobs: {
              python: {
                id: 2099,
                status: "done" as const,
                pr: 150,
                startedBy: "anna",
                startedAt: "2026-08-12T08:00:00Z",
                mergedBy: null,
                mergedAt: null,
                error: null,
              },
            },
          }
        : r,
    );
    resultPage("/generation/billing-api/result/v1/v1_payments", [[keys.genResources("billing-api"), stale]]);

    await screen.findByRole("heading", { name: "billing_api.payments" });
    toggle("payments.list()");
    send("payments.list()");

    expect(await screen.findByText("That did not go through")).toBeInTheDocument();
    expect(screen.getByText("payments has no pull request on Python SDK")).toBeInTheDocument();
    expect(within(operation("payments.list()")).getByText("not run")).toBeInTheDocument();
    expect(within(operation("payments.list()")).getByRole("button", { name: "Send request" })).toBeEnabled();
    fireEvent.click(screen.getByRole("button", { name: "Dismiss" }));
    await waitFor(() => expect(screen.queryByText("That did not go through")).toBeNull());

    // a refused refresh fetches the jobs again, and the page learns there is no such job
    fireEvent.click(screen.getByRole("button", { name: "Refresh PR state" }));

    expect(await screen.findByText("Page not found.")).toBeInTheDocument();
    expect(screen.getByRole("link", { name: "billing-api layout" })).toHaveAttribute("href", "/generation/billing-api");
  });
});

const CONTACTS = "/generation/customer-core/result/v1/c_contacts";
const LLM_ERROR = "LLM backend unavailable — ollama refused the connection after 3 retries";
const FAILED_HINT =
  "Nothing was written and no pull request was opened. The layout and its confirmations are untouched — retry once the LLM backend answers again.";
const contactsJob = () => generationResources("customer-core").find((r) => r.id === "c_contacts")?.jobs.python;

describe("the result of contacts: its generation failed", () => {
  it("says the generation failed, what went wrong and that nothing was written, and offers to retry", async () => {
    resultPage(CONTACTS);

    expect(await screen.findByRole("heading", { name: "customer_core.contacts" })).toBeInTheDocument();
    expect(screen.getByText("Failed")).toBeInTheDocument();
    expect(screen.getByText("Python SDK")).toBeInTheDocument();
    expect(screen.getByText(new RegExp(`^job #2094 · started by ivan · ${DATE}$`))).toBeInTheDocument();
    expect(screen.getByRole("link", { name: "customer-core layout" })).toHaveAttribute(
      "href",
      "/generation/customer-core",
    );

    expect(screen.getByText("Generation failed — LLM backend unavailable")).toBeInTheDocument();
    expect(screen.getByText(LLM_ERROR)).toBeInTheDocument();
    expect(screen.getByText(FAILED_HINT)).toBeInTheDocument();
    // ivan confirmed the layout before the generation he started (owner decision), so nothing holds a retry
    expect(screen.getByRole("button", { name: "Retry generation" })).toBeEnabled();
    expect(screen.queryByText("confirm the layout first")).toBeNull();
    expect(screen.queryByText(/highlighted field/)).toBeNull();
    expect(screen.queryByRole("link", { name: "open spec" })).toBeNull();

    // nothing was opened, so there is nothing to review or call
    expect(screen.queryByRole("link", { name: /^PR #/ })).toBeNull();
    expect(screen.queryByRole("button", { name: "Refresh PR state" })).toBeNull();
    expect(screen.queryByText("Live check")).toBeNull();
    expect(screen.queryByText(/^Generating —/)).toBeNull();
  });

  it("retries: a new job runs in place of the failed one, started by the signed-in user", async () => {
    resultPage(CONTACTS);

    fireEvent.click(await screen.findByRole("button", { name: "Retry generation" }));

    expect(await screen.findByText("In progress")).toBeInTheDocument();
    expect(screen.getByText("Generating — job #2101")).toBeInTheDocument();
    expect(screen.getByText("generation job started just now")).toBeInTheDocument();
    expect(screen.queryByText("Generation failed — LLM backend unavailable")).toBeNull();
    expect(screen.queryByText(LLM_ERROR)).toBeNull();
    expect(screen.queryByRole("button", { name: "Retry generation" })).toBeNull();
    expect(location()).toBe(CONTACTS);

    expect(contactsJob()).toEqual({
      id: 2101,
      status: "running",
      pr: null,
      startedBy: "ada@otc.test",
      startedAt: expect.any(String),
      mergedBy: null,
      mergedAt: null,
      error: null,
    });
    // the band no longer counts it as failed
    expect(generationAttention().find((r) => r.code === "gen_failed")).toBeUndefined();
  });

  it("holds a retry for what holds Generate on the spec, and names the first reason beside it", async () => {
    const unconfirmed = generationResources("customer-core").map((r) =>
      r.id === "c_contacts" ? { ...r, confirmedBy: null, confirmedAt: null } : r,
    );
    const { unmount } = panel(CONTACTS, [[keys.genResources("customer-core"), unconfirmed]]);

    expect(await screen.findByText(LLM_ERROR)).toBeInTheDocument();
    expect(screen.getByRole("button", { name: "Retry generation" })).toBeDisabled();
    expect(screen.getByText("confirm the layout first")).toBeInTheDocument();
    fireEvent.click(screen.getByRole("link", { name: "edit layout" }));
    expect(location()).toBe("/generation/customer-core/layout");
    unmount();

    // confirmed, but a field of its class is left to decide
    const spec = generationSpec("customer-core", "c_contacts");
    const [contact] = spec.classes;
    const issue = {
      problem: "unknown_type" as const,
      text: "Type not recognized",
      options: [{ type: "String", note: "keep the raw value" }],
      docs: [],
      choice: null,
    };
    const open = {
      ...spec,
      classes: [{ ...contact, fields: contact.fields.map((f) => (f.name === "name" ? { ...f, issue } : f)) }],
    };
    panel(CONTACTS, [[keys.genSpec("customer-core", "c_contacts"), open]]);

    expect(await screen.findByText("decide the highlighted field first")).toBeInTheDocument();
    expect(screen.getByRole("button", { name: "Retry generation" })).toBeDisabled();
    expect(screen.queryByText("confirm the layout first")).toBeNull();
    expect(screen.queryByRole("link", { name: "edit layout" })).toBeNull();
    expect(contactsJob()).toMatchObject({ id: 2094, status: "failed", error: LLM_ERROR });

    // the field is highlighted on the spec, where the reason's link leads (owner decision)
    fireEvent.click(screen.getByRole("link", { name: "open spec" }));
    expect(location()).toBe("/generation/customer-core/spec/v1/c_contacts");
    const name = await screen.findByRole("group", { name: "name" });
    expect(name.firstElementChild).toHaveClass("bg-amber-50");
    expect(within(name).getByRole("button", { name: "unknown type" })).toBeInTheDocument();
  });

  it("says why a retry was refused, and picks the job up as it is now", async () => {
    // the page still shows the failed job; meanwhile ivan has retried it
    const failed = generationResources("customer-core");
    startGeneration("customer-core", "c_contacts", "python", "ivan");
    resultPage(CONTACTS, [[keys.genResources("customer-core"), failed]]);

    fireEvent.click(await screen.findByRole("button", { name: "Retry generation" }));

    expect(await screen.findByText("That did not go through")).toBeInTheDocument();
    expect(screen.getByText("contacts is generating on Python SDK")).toBeInTheDocument();
    // the refusal fetches the jobs again: ivan's is the one shown now, and nobody's replaced it
    expect(await screen.findByText("Generating — job #2101")).toBeInTheDocument();
    expect(screen.queryByText(LLM_ERROR)).toBeNull();
    expect(screen.queryByRole("button", { name: "Retry generation" })).toBeNull();
    expect(contactsJob()).toMatchObject({ id: 2101, status: "running", startedBy: "ivan" });

    fireEvent.click(screen.getByRole("button", { name: "Dismiss" }));
    await waitFor(() => expect(screen.queryByText("That did not go through")).toBeNull());
  });

  it("opens from the failed job on the card and leads back to it", async () => {
    panel("/generation/customer-core");

    fireEvent.click(await screen.findByRole("link", { name: "failed" }));

    expect(location()).toBe(CONTACTS);
    expect(await screen.findByText(LLM_ERROR)).toBeInTheDocument();
    fireEvent.click(screen.getByRole("link", { name: "customer-core layout" }));
    expect(location()).toBe("/generation/customer-core");
  });
});

const CUSTOMERS = "/generation/customer-core/result/v1/c_customers";
const MERGED_NOTE = "Merged — this resource left Generation and is maintained from the Maintenance panel now.";

describe("the result of customers: merged", () => {
  it("shows the pull request merged, who merged it and when, and that the resource left for Maintenance", async () => {
    resultPage(CUSTOMERS);

    expect(await screen.findByRole("heading", { name: "customer_core.customers" })).toBeInTheDocument();
    expect(screen.getByText("Merged")).toBeInTheDocument();
    expect(screen.getByText("Python SDK")).toBeInTheDocument();
    expect(
      screen.getByText(
        new RegExp(`^4 methods · 1 class · generated by ivan · ${DATE} · merged by valeriia · ${DATE}$`),
      ),
    ).toBeInTheDocument();
    expect(screen.getByRole("link", { name: "customer-core layout" })).toHaveAttribute(
      "href",
      "/generation/customer-core",
    );

    const pr = screen.getByRole("link", { name: "PR #122" });
    expect(pr).toHaveAttribute("href", "https://github.com/opentelekomcloud/python-t-cloud/pull/122");
    expect(pr).toHaveAttribute(
      "title",
      "feat(customers): generate customer_core.customers from v1 docs · branch gen/customer_core-customers",
    );
    expect(screen.getByText("merged")).toBeInTheDocument();
    expect(screen.queryByText("open")).toBeNull();
    // a merge is the pull request's last state: there is nothing left to pick up
    expect(screen.queryByRole("button", { name: "Refresh PR state" })).toBeNull();

    expect(screen.getByText(MERGED_NOTE)).toBeInTheDocument();
    // there is no way into Maintenance (owner decision)
    expect(screen.queryByRole("button", { name: /Maintenance/ })).toBeNull();
    expect(screen.queryByRole("link", { name: /Maintenance/ })).toBeNull();

    expect(screen.queryByText(/^Generation failed/)).toBeNull();
    expect(screen.queryByRole("button", { name: "Retry generation" })).toBeNull();
    expect(screen.queryByText(/^Generating —/)).toBeNull();
  });

  it("keeps the live check of its GET operations", async () => {
    resultPage(CUSTOMERS);

    await screen.findByRole("heading", { name: "customer_core.customers" });
    expect(screen.getByText("Live check")).toBeInTheDocument();
    // the list and the get; the update and the delete are not called live (owner decision)
    expect(screen.getAllByRole("group")).toHaveLength(2);
    expect(within(operation("customers.list()")).getByText("/v1/customers")).toBeInTheDocument();
    expect(within(operation("customers.get()")).getByText("/v1/customers/{customer_id}")).toBeInTheDocument();
    expect(screen.queryByText(/customers\.(update|delete)\(\)/)).toBeNull();

    toggle("customers.list()");
    fireEvent.click(params("customers.list()", "Query"));
    expect(within(operation("customers.list()")).getByRole("textbox", { name: "segment" })).toBeInTheDocument();
    send("customers.list()");

    const list = operation("customers.list()");
    expect(await within(list).findByText("live ok")).toBeInTheDocument();
    expect(JSON.parse(within(list).getByText(/"count": 1/).textContent ?? "")).toEqual({
      customers: [{ id: "customer-3f9c", name: "name-value", segment: "segment-value", active: true }],
      count: 1,
    });
  });

  it("opens from the merged job on the card and leads back to it", async () => {
    panel("/generation/customer-core");

    fireEvent.click(await screen.findByRole("link", { name: "merged · PR 122" }));

    expect(location()).toBe(CUSTOMERS);
    expect(await screen.findByText(MERGED_NOTE)).toBeInTheDocument();
    fireEvent.click(screen.getByRole("link", { name: "customer-core layout" }));
    expect(location()).toBe("/generation/customer-core");
  });
});

describe("a viewer", () => {
  beforeEach(() => {
    session.token = tokenWithRoles("viewer");
  });

  it("reads why a generation failed, but is not offered to retry it", async () => {
    resultPage(CONTACTS);

    expect(await screen.findByText("Generation failed — LLM backend unavailable")).toBeInTheDocument();
    expect(screen.getByText(LLM_ERROR)).toBeInTheDocument();
    expect(screen.getByText(FAILED_HINT)).toBeInTheDocument();
    expect(screen.queryByRole("button", { name: "Retry generation" })).toBeNull();
  });

  it("reads the pull request and may call the GET operations, but is not offered to pick up its state", async () => {
    resultPage();

    expect(await screen.findByRole("link", { name: "PR #131" })).toBeInTheDocument();
    expect(screen.getByText("open")).toBeInTheDocument();
    expect(screen.queryByRole("button", { name: "Refresh PR state" })).toBeNull();

    // a live GET changes nothing in the panel or the tenant
    expect(screen.getByRole("button", { name: "Run all" })).toBeInTheDocument();
    toggle("invoices.list()");
    send("invoices.list()");
    expect(await within(operation("invoices.list()")).findByText("live ok")).toBeInTheDocument();
  });

  it("reads a merged result as a worker does: who merged it, where it went, and the live check", async () => {
    resultPage(CUSTOMERS);

    expect(await screen.findByText(MERGED_NOTE)).toBeInTheDocument();
    expect(screen.getByText(new RegExp(`· merged by valeriia · ${DATE}$`))).toBeInTheDocument();
    expect(screen.getByRole("link", { name: "PR #122" })).toBeInTheDocument();
    expect(screen.getByRole("button", { name: "Run all" })).toBeInTheDocument();
  });
});

describe("other results on the mock", () => {
  it("shows a generation still running: its job, and neither a pull request nor a live check", async () => {
    confirmResource("billing-api", "v2_invoices", "valeriia");
    panel("/generation/billing-api/spec/v2/v2_invoices");

    fireEvent.click(await screen.findByRole("button", { name: "Generate for Python SDK" }));

    await waitFor(() => expect(location()).toBe("/generation/billing-api/result/v2/v2_invoices"));
    expect(await screen.findByText("In progress")).toBeInTheDocument();
    expect(screen.getByText("generation job started just now")).toBeInTheDocument();
    expect(screen.getByText("Generating — job #2101")).toBeInTheDocument();
    expect(
      screen.getByText("Rendering templates, resolving FIXME placeholders, opening a pull request…"),
    ).toBeInTheDocument();
    expect(screen.queryByRole("link", { name: /^PR #/ })).toBeNull();
    expect(screen.queryByText("Live check")).toBeNull();
    // it was started from the spec, so the way back leads there
    expect(screen.getByRole("link", { name: "invoices spec" })).toHaveAttribute(
      "href",
      "/generation/billing-api/spec/v2/v2_invoices",
    );
  });

  it("does not open a result where the resource was never generated", async () => {
    const { unmount } = resultPage("/generation/billing-api/result/v1/v1_payments");

    expect(await screen.findByText("Page not found.")).toBeInTheDocument();
    expect(screen.getByRole("link", { name: "billing-api layout" })).toHaveAttribute("href", "/generation/billing-api");
    unmount();

    // generated on Python SDK, not on Ansible modules
    resultPage("/generation/billing-api/result/v1/v1_invoices?target=ansible");
    expect(await screen.findByText("Page not found.")).toBeInTheDocument();
    expect(screen.getByRole("link", { name: "billing-api layout" })).toHaveAttribute(
      "href",
      "/generation/billing-api?target=ansible",
    );
  });

  it("does not open a resource under another version, nor a service that is not in Generation", async () => {
    const { unmount } = resultPage("/generation/billing-api/result/v2/v1_invoices");

    expect(await screen.findByText("Page not found.")).toBeInTheDocument();
    unmount();

    resultPage("/generation/sms-gateway/result/v1/v1_invoices");
    expect(await screen.findByText("Page not found.")).toBeInTheDocument();
    expect(screen.getByRole("link", { name: "All services" })).toHaveAttribute("href", "/generation");
  });

  it("is backed by a mock that calls only GET operations of generated code, and takes GitHub's word on a merge", () => {
    expect(() =>
      liveCall("billing-api", "v1_invoices", "python", "e3", { path: {}, query: {} }),
    ).toThrow("Only GET operations are called live, not POST /v1/billing/invoices");
    expect(() =>
      liveCall("billing-api", "v1_invoices", "python", "e5", { path: {}, query: {} }),
    ).toThrow("invoices has no endpoint e5");
    expect(() =>
      liveCall("customer-core", "c_contacts", "python", "c5", { path: { customer_id: "c-1" }, query: {} }),
    ).toThrow("contacts has no pull request on Python SDK");
    expect(() => refreshPullRequest("billing-api", "v1_invoices", "ansible")).toThrow(
      "invoices has no pull request on Ansible modules",
    );

    // GitHub has no merge of PR 122 to report beyond the one the panel knows
    const before = generationResources("customer-core").find((r) => r.id === "c_customers")?.jobs.python;
    refreshPullRequest("customer-core", "c_customers", "python");
    expect(generationResources("customer-core").find((r) => r.id === "c_customers")?.jobs.python).toEqual(before);
  });
});

describe("the way in and out", () => {
  it("opens from the card and leads back to it", async () => {
    panel("/generation/billing-api");

    fireEvent.click(await screen.findByRole("link", { name: "in review · PR 131" }));

    expect(location()).toBe("/generation/billing-api/result/v1/v1_invoices");
    fireEvent.click(await screen.findByRole("link", { name: "billing-api layout" }));
    expect(location()).toBe("/generation/billing-api");
  });

  it("opens from the spec and leads back to it", async () => {
    panel("/generation/billing-api/spec/v1/v1_invoices");

    fireEvent.click(await screen.findByRole("link", { name: "in review · PR 131" }));

    expect(location()).toBe("/generation/billing-api/result/v1/v1_invoices");
    fireEvent.click(await screen.findByRole("link", { name: "invoices spec" }));
    expect(location()).toBe("/generation/billing-api/spec/v1/v1_invoices");
    expect(await screen.findByText(/^Generation spec · Python SDK/)).toBeInTheDocument();
  });
});

